---
image: ruby:2.6.3

stages:
- sanity
- test
- package

before_script:
- apt-get install -y libjack0 libjack-dev
- apt-get install -y libportaudiocpp0 portaudio19-dev libmpg123-dev
- gem install bundler
- bundle install

maps:validate:
  stage: sanity
  script: bundle exec rake maps:validate

specs:
  stage: test
  script: bundle exec rspec
