---
image: ruby:2.6.3

stages: 
- sanity
- test
- package

before_script:
- bundle install

map-validation:
  stage: sanity
  script: bundle exec rake validate_maps

specs:
  stage: test
  script: bundle exec rspec
